# permissions for end users to edit airbytes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: airbyte-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: airbyte-operator
    app.kubernetes.io/part-of: airbyte-operator
    app.kubernetes.io/managed-by: kustomize
  name: airbyte-editor-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - airbytes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - airbytes/status
  verbs:
  - get
